### ISSUE TITLE
Export on standalone ami fails if crossfade applied.

### ISSUE THREAD

**Issue by gaborkukucska** [moviemasher/angular-moviemasher#11]
It fails to export if crossfade applied anywhere, but it works with themes (title and color)...

AMI used: https://aws.amazon.com/marketplace/pp/B00QKW0P2A
Only change: Implemented SSL
Error:  failed to render Error configuring filters.

**Comment by syntropo** [comment]
I'm not able to replicate this issue - crossfade seems to work with both themes and videos. Could you provide a copy of your mash json?

**Comment by gaborkukucska** [comment]
Ok I did some more digging and I've figured out what is going on. the default "crossfade" effect only works if it is applied between two clips and fails if it is used at the end of a clip to fade to black.

I'm a videographer and we always use the crossfade in editing to fade from / to black by dropping it on the beginning / end of a clip... there are the "dip to black" and "dip from black" effects too but crossfade works IF there is no other video clip is placed at a lower video track.

I leave this up to you to decide but I think it should work when applied to a single clip, however in that case it also need to realise whether it is applied at the beginning or the end of a clip and fade in or out accordingly.

**Comment by syntropo** [comment]
Yeah, the transitions used to work like this in the last version. It's a bit more complicated now though, since everything's mapping directly to the FFMpeg effects - transitions are not actually supported in FFMpeg, unfortunately.

**Comment by gaborkukucska** [comment]
not a biggie... transitions are useless if you ask me... no pro uses transitions... we do need to be able to fade from and to black. is there a way to do that with ffmpeg?

I know this is unrelated to the original issue and we can potentially implement ourselves just wondering if you might know of a good resource to start with. I know the command:

`ffmpeg -i input.mp4 -vf "fade=in:0:25,fade=out:975:25" -acodec copy out.mp4`

but how does that work as a "transition" I wonder

**Comment by syntropo** [comment]
Just put a Color theme at the end, set to black

**Comment by gaborkukucska** [comment]
Got ya! :) :+1: thanks!
