### ISSUE TITLE
File after successful export on standalone ami isn't represented in UI.

### ISSUE THREAD

**Issue by gaborkukucska** [moviemasher/angular-moviemasher#12]
When the export is successful, the file does not get downloaded not displayed through the UI, the only way to get it is to sftp into the instance and downloading it from the /user-media/username/ folder where actually finding the right subfolder is a bit of a job :) .

**Comment by syntropo** [comment]
What error do you get in the browser when it attempts to load the rendered file?

**Comment by gaborkukucska** [comment]
No error in browser, just finishes the export and nothing happens. Been using chrome. Will try other browsers and I'll check the logs too and get back to you.

**Comment by gaborkukucska** [comment]
Same in opera and here is the log:

`19:59:41 export_monitor.php {"job":"0BC29000-FCA4-43D1-B648-D38D5B8FF015","id":"e0306506-aed4-46b3-a331-d36f9b6d818f","uid":"gabor","type":"video","extension":"mp4","error":"","log":"# Logfile created on 2016-03-31 19:59:26 +0000 by logger.rb/41954\n","commands":["ffmpeg -y -filter_complex 'color=color=0x000000:duration=7.5:size=512x288:rate=30[layer0];movie=filename=/tmp/moviemasher/download/1987c807c645019109a61e1d6f47e659acfb29fb89dff7621e90ec1b6cc5ec1b/downloaded.mp4,trim=duration=7.5,fps=fps=30,setpts=expr=PTS-STARTPTS,scale=width=512.0:height=288.0,setsar=sar=1.0:max=1.0[layer1];[layer0][layer1]overlay=x=0.0:y=0.0'  -t 7.5 -s 512x288 -c:v libx264 -preset ultrafast -level 41 -movflags faststart -b:v 2000k -r:v 30 -metadata title=\"New Untitled Mash\" -pass 1 -passlogfile /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/pass-fee98080-d9a8-0133-282f-22000b91c0e4 -f mp4 /dev/null","ffmpeg -y -filter_complex 'color=color=0x000000:duration=7.5:size=512x288:rate=30[layer0];movie=filename=/tmp/moviemasher/download/1987c807c645019109a61e1d6f47e659acfb29fb89dff7621e90ec1b6cc5ec1b/downloaded.mp4,trim=duration=7.5,fps=fps=30,setpts=expr=PTS-STARTPTS,scale=width=512.0:height=288.0,setsar=sar=1.0:max=1.0[layer1];[layer0][layer1]overlay=x=0.0:y=0.0'  -t 7.5 -s 512x288 -c:v libx264 -preset ultrafast -level 41 -movflags faststart -b:v 2000k -r:v 30 -metadata title=\"New Untitled Mash\" -pass 2 -passlogfile /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/pass-fee98080-d9a8-0133-282f-22000b91c0e4 /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/fee88940-d9a8-0133-282b-22000b91c0e4/concat-0.mp4","ffmpeg -y -filter_complex 'color=color=0x000000:duration=3.7:size=512x288:rate=30[layer0];movie=filename=/tmp/moviemasher/download/4106fa37186e6bd1aea7071cec9fc17877d50b59e54c2de1b91ecda91ea26c1d/downloaded.mp4,trim=duration=3.7,fps=fps=30,setpts=expr=PTS-STARTPTS,scale=width=512.0:height=288.0,setsar=sar=1.0:max=1.0[layer1];[layer0][layer1]overlay=x=0.0:y=0.0'  -t 3.7 -s 512x288 -c:v libx264 -preset ultrafast -level 41 -movflags faststart -b:v 2000k -r:v 30 -metadata title=\"New Untitled Mash\" -pass 1 -passlogfile /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/pass-02ab83c0-d9a9-0133-2830-22000b91c0e4 -f mp4 /dev/null","ffmpeg -y -filter_complex 'color=color=0x000000:duration=3.7:size=512x288:rate=30[layer0];movie=filename=/tmp/moviemasher/download/4106fa37186e6bd1aea7071cec9fc17877d50b59e54c2de1b91ecda91ea26c1d/downloaded.mp4,trim=duration=3.7,fps=fps=30,setpts=expr=PTS-STARTPTS,scale=width=512.0:height=288.0,setsar=sar=1.0:max=1.0[layer1];[layer0][layer1]overlay=x=0.0:y=0.0'  -t 3.7 -s 512x288 -c:v libx264 -preset ultrafast -level 41 -movflags faststart -b:v 2000k -r:v 30 -metadata title=\"New Untitled Mash\" -pass 2 -passlogfile /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/pass-02ab83c0-d9a9-0133-2830-22000b91c0e4 /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/fee88940-d9a8-0133-282b-22000b91c0e4/concat-1.mp4","ecasound  -a:1 -i playat,0.0,select,0.0,7.0,/tmp/moviemasher/download/b616e6464af6b15354f04840572a56391fabb737d25339c3aa4f617ab7f42c88/downloaded-intermediate.wav -a:2 -i playat,6.3,select,0.0,4.9,/tmp/moviemasher/download/b616e6464af6b15354f04840572a56391fabb737d25339c3aa4f617ab7f42c88/downloaded-intermediate.wav -a:3 -i playat,0.0,select,0.0,7.5,/tmp/moviemasher/download/1987c807c645019109a61e1d6f47e659acfb29fb89dff7621e90ec1b6cc5ec1b/downloaded-intermediate.wav -a:4 -i playat,7.5,select,0.0,3.7,/tmp/moviemasher/download/4106fa37186e6bd1aea7071cec9fc17877d50b59e54c2de1b91ecda91ea26c1d/downloaded-intermediate.wav -a:5 -i playat,0,tone,sine,0,11.2 -a:all -z:mixmode,sum -o /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/fee88940-d9a8-0133-282b-22000b91c0e4/audio-3e336efb07d206b3a6cf94bc3179374249c7e30a449242e1bd150a795f92d676.wav","ffmpeg -y  -i /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/fee88940-d9a8-0133-282b-22000b91c0e4/audio-3e336efb07d206b3a6cf94bc3179374249c7e30a449242e1bd150a795f92d676.wav -r:v 30 -auto_convert 1 -i '/tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/fee88940-d9a8-0133-282b-22000b91c0e4/concat.txt' -c:v copy -af 'atrim=start=0.0:duration=11.2,asetpts=expr=PTS-STARTPTS' -async 1 -t 11.2 -b:a 224k -r:a 44100 -c:a aac -strict experimental -metadata title=\"New Untitled Mash\" /tmp/moviemasher/render/fee6f0e0-d9a8-0133-281a-22000b91c0e4/fee88940-d9a8-0133-282b-22000b91c0e4.mp4"]}
19:59:41 export_monitor.php {"completed":1,"source":"\/user-media\/gabor\/e0306506-aed4-46b3-a331-d36f9b6d818f\/0BC29000-FCA4-43D1-B648-D38D5B8FF015.mp4","ok":1}`

**Comment by syntropo** [comment]
The file is not expected to download once the rendering is complete. The View button should be enabled though, which should let you see and download it.

**Comment by gaborkukucska** [comment]
Oh I see! Cool that works then :) I'd suggest swapping the export and view buttons around then to make it more intuitive. Thanks!

**Comment by TharakaRumeshJeewantha** [comment]
I downloaded Angular-MovieMasher on GitHub and I tried to run it on my WAMP and XAMPP server. But It must need to some configuration. please can you tell me how to do this configurations and I want to remove docker part on this project. please help me to do this.

![aaa](https://user-images.githubusercontent.com/25604416/49323708-79cfa500-f545-11e8-8318-a5126d9e7388.PNG)

**Comment by syntropo** [comment]
You'll want to read through the 'Installation' and 'Install on your web server' sections of the README for this project. Please understand that the moviemasher.rb must also be utilized, but should be installed on a separate server since it is so resource intensive.
