### ISSUE TITLE
SSL related error - Error executing "SendMessage"

### ISSUE THREAD

**Issue by gaborkukucska** [moviemasher/angular-moviemasher#13]
Hi @syntropo,

I'm getting the following error if I turn on ssl on the server:

`Error executing "SendMessage" on "https://sqs.ap-southeast-2.amazonaws.com/078148713567/DIY-QueueMM-1DX4WPVS4YKVA"; AWS HTTP error: cURL error 77:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**The cURL error 77 is:**
CURLE_SSL_CACERT_BADFILE (77)
Problem with reading the SSL CA cert (path? access rights?)

However when I check the diy.50dmc.com on https://www.sslshopper.com/ it all looks good. Any ideas?

**Comment by syntropo** [comment]
I'm not sure, but that does sound like a likely cause. You might check with the aws-php-sdk team, since it's their code generating the error there. I will be building a new AMI shortly and can incorporate any needed changes to permissions or whatever.

**Comment by gaborkukucska** [comment]
Thanks for your prompt reply @syntropo ! I'll ask the aws-php-sdk team and report back! Thanks!

**Comment by gaborkukucska** [comment]
Just letting you know that I'm waiting for AWS to enable business aws support so I can open the technical ticket...

**Comment by gaborkukucska** [comment]
I have fixed this by this pointing me to the right direction:
http://serverfault.com/questions/394815/how-to-update-curl-ca-bundle-on-redhat

Making sure that the CA bundle file here: 
/etc/pki/tls/certs/ca-bundle.crt

is updated with more certificates:
https://curl.haxx.se/ca/cacert.pem (MIGHT BE TOO MANY !!!)

AND that it is world readable : 
`sudo chmod 644 /etc/pki/tls/certs/ca-bundle.crt`

And that's it :)

If anyone is interested I've followed this guide to get ssl setup on the UI instance:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-an-instance.html
