### ISSUE TITLE
Using full file URL for uploading process in 4.12 angular movie masher

### ISSUE THREAD

**Issue by testingtry** [moviemasher/angular-moviemasher#14]
Hi,

How to use file URL'S at the the time of uploading in amm_browser

Thanks

**Comment by syntropo** [comment]
Do you really mean URLs starting with 'file://' ?

**Comment by testingtry** [comment]
No Douglus,

file Path is

http://images.fonearena.com/blog/wp-content/uploads/2013/11/Lenovo-p780-camera-sample-2.jpg

i have all the images files,audio and videos with are uploded in server with http file URLS,How to move those files to movie masher

**Comment by testingtry** [comment]
hi Douglus,

How can i use already uploaded files(https://) path of a file in to the movie masher,Am trying to upload files in import_upload.php (but missing the functionality in import_init and files),Can u guide me how to do the process

**Comment by syntropo** [comment]
This seems a bit out of scope for the project. The best approach would probably be to solicit the URL through the UI somehow and pass it to a new endpoint you create that constructs an import job out of it, passing it to the queue.
