### ISSUE TITLE
Docker instances - "error":"Required type parameters omitted"

### ISSUE THREAD

**Issue by hanklank** [moviemasher/angular-moviemasher#15]
I did set up the docker instances as described.
However when drag and dropping a videofile to the gui (with media set as video), I get the error 
"error":"Required type parameters omitted""

A tail in the angular-moviemasher.log gives 
11:35:17 import_init.php Array
(
    [file] => svt_barn24_2016-03-27_010000_030000.mp4
    [size] => 398706725
    [type] => video/mp4
)

11:35:17 import_init.php Array
(
    [file] => svt_barn24_2016-03-27_010000_030000.mp4
    [size] => 398706725
    [type] => 
    [uid] => a
    [mime] => video/mp4
)

11:35:17 import_init.php {"api":{"id":"98692F3C-4E52-407E-8167-DB808D79479F","type":"video","extension":"mp4","label":"svt_barn24_2016-03-27_010000_030000.mp4"},"data":{"id":"98692F3C-4E52-407E-8167-DB808D79479F","type":"video","extension":"mp4"},"endpoint":"php\/import_upload.php","method":"post","ok":1}
11:35:17 import_upload.php {"error":"Required type parameters omitted"}

So, from what i can see the endpoint doesn't pick up the type parameter even though it's sent?

**Comment by hanklank** [comment]
It seems that type isn't set in import_init.php

  $request['mime'] = (empty($request['type']) ? '' : $request['type']);
  $request['type'] = '';

**Comment by syntropo** [comment]
Hmmm.... I'm not able to replicate the issue in docker - which of the compose files are you using? Or if you're not using docker-compose, how did you launch the containers? 

That php code in import_init.php is correct, though confusing! The angular client is sending a mime type in the type parameter, and we're looking to have just the first component (video, audio, image) in the return type that's ultimately passed back to import_upload.php. It seems like your deployment is having trouble confirming the mime type of the file - does it handle uploading of images, audio, and perhaps other video files correctly?
