### ISSUE TITLE
KINDLY TELL IN WHAT COMMAND TO RUN THIS APPLICATION ?

### ISSUE THREAD

**Issue by sonydaman** [moviemasher/angular-moviemasher#16]
How we can run this application ?
There is only installation telling where is run in read me file ?

==============================

Developer Setup

Docker is used extensively to develop this project, specifically to update components using standard tools like npm, bower, grunt, and composer. Though not routinely tested, these same tools might work outside Docker - just cd to project directory and execute:

    npm install

    bower install --production

    grunt

    cd app/php/service/aws

    composer install

=========================================================

**Comment by syntropo** [comment]
Clear instructions are under the **Docker Usage** section, or if you want to run the developer image with more debugging just read a little further down from that snippet you pasted. I'd suggest reading the entire file since it explains a lot.
