### ISSUE TITLE
Installation without shell access?

### ISSUE THREAD

**Issue by Gantron1** [moviemasher/angular-moviemasher#17]
I'm on a shared host and don't have shell access. How can I install in this scenario? I do have XAMPP installed on a local machine, and I've used it to install MediaWiki and some extensions that require Composer commands issued from the shell. Can I do something similar with MovieMasher and install locally, then upload the resultant directory via FTP to my shared sever, or is there an easier way?

**Comment by syntropo** [comment]
What all are you trying to install? You should be able to install angular-moviemasher by simply uploading the files (executing composer is not required) and either adding to PHP's include_path or supplying a full path to moviemasher.ini in configutils.php. It's highly unlikely you'll be able to install moviemasher.rb, ffmpeg and supporting libraries - this is not at all recommended anyway. Typically folks will run this in AWS and utilize SQS and S3.
