### ISSUE TITLE
Audio clip icon will not be shown

### ISSUE THREAD

**Issue by StudChris** [moviemasher/angular-moviemasher#26]
I have noticed that the audio clip icon is 1px high. This issue is also available in the demo.

![demo](https://user-images.githubusercontent.com/28002711/28200136-773569a6-686a-11e7-9893-c68c0a06d2be.PNG)

I have tried to fix it in the clip.html and maybe you have a better solution.

``` <img style="height: 60px" ng-src="{{amm_media_icon_url($amm.player.media(clip))}}" ```

In addition, I have an improvement suggestion. The audio icon could be over the entire length.

![unbenannt](https://user-images.githubusercontent.com/28002711/28200462-8e490f74-686c-11e7-99dd-8916e4efaf06.PNG)

The icon fits even with zoom.

```<div style="width: 100%" class="amm-timeline-clip-icon amm-mouseless" ng-if="amm_media_icon_url($amm.player.media(clip))"><img style="height: 60px; width: 100%" ng-src="{{amm_media_icon_url($amm.player.media(clip))}}" crossorigin='anonymous' /></div>```

The problem is that other icons now get streched too.

![unbenannt2](https://user-images.githubusercontent.com/28002711/28200640-ae072160-686d-11e7-85be-697443eee414.PNG)

Another improvement could be preview icons over the whole video clip.

**Comment by syntropo** [comment]
Thanks for the bug report on the audio icons. I'm not sure we want to stretch or dramatically crop the visual icons to fit.

**Comment by syntropo** [comment]
Fixed the waveform display in 1.0.22
