### ISSUE TITLE
Uploading media assets from the media URL (Ver. 4.0.21)

### ISSUE THREAD

**Issue by rickcha** [moviemasher/angular-moviemasher#27]
Hi there, 

I've been trying to accomplish this for the past few days and could not find the solution. I hope I could get some help.

I used AWS AMI to host a moviemasher. It works very well and everyone likes it. The problem is that I only know I can drag and drop files and load them as assets although I have another bucket that contains all my existing videos. Alternatively, I want to provide a way to load assets using the media URLs. Is there a way to achieve this workflow?

Thank you for your help !

**Comment by syntropo** [comment]
Sure, you can use the same mechanisms to initiate jobs for previously uploaded assets. Careful study of the logs in angular-moviemasher will reveal the syntax of the jobs that are getting posted. The apiutils.php file contains several methods that help construct these job descriptions for the transcoder.
