### ISSUE TITLE
Am I missing something - please help Version 1.0.18 (4.0.21)

### ISSUE THREAD

**Issue by gregmcewanmarriott** [moviemasher/angular-moviemasher#28]
Hi All - I run an Ubuntu install on DigitalOcean - just want to check my steps as I get the UI to load beautifully, uploads get to 100% - in FTP i see the uploaded file in user-media created perfect -
But on 100% get error that there is an error in config,,,

i downloaded latest Version 1.0.18 (4.0.21)
ftp the folder angular-moviemasher with subdirs app, bower_components, src etc (all files)
I could not place the moviemasher.ini outside my /var/www/html/ folder so placed it in /var/www/html/angular-moviemasher/app/php/include
I also added to the top of apiutils.php the following `include_once(dirname(__FILE__) . '/moviemasher.ini');`
I added this to my php.ini file (on server) `include_path = ".:/var/www/html/angular-moviemasher/app/php/include"
date.timezone = UTC
upload_max_filesize = 200M
post_max_size = 200M
max_input_time = 600`

User directories are created fine and upload puts file in folder  logfile below - 

what am i missing?

log files,,,,

19:35:46 import_init.php Array
(
    [file] => 84b07392-925a-416d-b2df-22f2b987ccac-original.jpeg
    [size] => 56908
    [type] => image/jpeg
)

19:35:46 import_init.php Array
(
    [file] => 84b07392-925a-416d-b2df-22f2b987ccac-original.jpeg
    [size] => 56908
    [type] => 
    [uid] => greg
    [mime] => image/jpeg
)

19:35:46 import_init.php {"api":{"id":"67B60D83-6E65-4F16-A1A3-2690CA3E5EB6","type":"image","extension":"jpeg","label":"84b07392-925a-416d-b2df-22f2b987ccac-original.jpeg"},"data":{"id":"67B60D83-6E65-4F16-A1A3-2690CA3E5EB6","type":"image","extension":"jpeg"},"endpoint":"php\/import_upload.php","method":"post","ok":1}
19:35:47 import_upload.php Saved to: /var/www/html/user-media/greg/67B60D83-6E65-4F16-A1A3-2690CA3E5EB6/original.jpeg
19:35:47 import_upload.php {"status":"uploaded ok","ok":1}
19:35:47 import_api.php Array
(
    [id] => 67B60D83-6E65-4F16-A1A3-2690CA3E5EB6
    [type] => image
    [extension] => jpeg
    [label] => 84b07392-925a-416d-b2df-22f2b987ccac-original.jpeg
)

19:35:47 import_api.php local request:
{"callbacks":[{"type":"file","trigger":"progress","method":"copy","directory":"\/var\/www\/html\/angular-moviemasher\/uploads","path":"{job.id}.json","data":{"job":"{job.id}","progress":"{job.progress}"}},{"type":"file","trigger":"complete","method":"copy","directory":"\/var\/www\/html\/angular-moviemasher\/uploads","path":"{job.id}.json","data":{"job":"{job.id}","id":"67B60D83-6E65-4F16-A1A3-2690CA3E5EB6","uid":"greg","extension":"jpeg","type":"image","label":"84b07392-925a-416d-b2df-22f2b987ccac-original.jpeg","error":"{job.error}","log":"{job.log}","commands":"{job.commands}","no_audio":"{job.inputs.0.no_audio}","no_video":"{job.inputs.0.no_video}"}}],"inputs":[{"type":"image","fill":"none","source":{"name":"original","extension":"jpeg","type":"file","method":"symlink","directory":"\/var\/www\/html\/user-media\/greg\/67B60D83-6E65-4F16-A1A3-2690CA3E5EB6"}}],"outputs":[{"type":"image","name":"0","path":"256x144x1","dimensions":"256x144","extension":"jpeg","quality":"1"}],"destination":{"type":"file","method":"move","directory":"\/var\/www\/html\/user-media\/greg\/67B60D83-6E65-4F16-A1A3-2690CA3E5EB6"}}
19:35:47 import_api.php {"monitor":{"job":"354E24CA-A9DC-4CCD-8697-7AF2FD431239"},"ok":1}

**Comment by syntropo** [comment]
Sorry I'm just seeing your post. When you get an error saying 'error in config' it's likely a problem in the moviemasher.ini file, or a problem reading it. You might make a new PHP page you can test with that simply tries to read in the configuration, as the other scripts do, outputting the error directly.
