### ISSUE TITLE
Audio Playback Issue

### ISSUE THREAD

**Issue by slsmithtx** [moviemasher/angular-moviemasher#29]
One of our customers is experiencing the following in the UI. He has a mash that has three videos one after the other in the timeline. He plays the mash, and it moves into the second video. He pauses the video and moves the position in the mash back into the first video. When he hits play again, he hears audio from both the first and second video until it gets back to the second video and it corrects itself. However, if he moves the position back to the first video while the mash is still playing, the issue doesn't happen.

**Comment by syntropo** [comment]
Fixed in version 4.0.22 of moviemasher.js
