### ISSUE TITLE
Icon/audio/wave are not generating and getting error while drop video/audio/image for mixture

### ISSUE THREAD

**Issue by JagrutDaveiLogix** [moviemasher/angular-moviemasher#31]
Hello There,
I setup angular-moviemasher script to local system.
1) When I upload new video,  Icon/audio/wave are not generating, that's why I can not see thumbnail image when select video from dropdown.
2) When I drag and drop video/audio/image file I am getting some errors and some warnings, they are as follow:
    Error - could not find registered filter overlay/scale/setsar
    Warning - filter not registered overlay/scale/setsar

Thanks

**Comment by syntropo** [comment]
Please describe your 'local' setup - are you using Docker or some other method? The angular code must register the modules it might encounter in a mash, before loading it.

**Comment by JagrutDaveiLogix** [comment]
Currently I am using http://localhost/moviemasher/app/.
Is it right or wrong ?

**Comment by syntropo** [comment]
It is wrong. You want to read the README for this project, specifically the Docker sections if you want to easily run locally.

**Comment by JagrutDaveiLogix** [comment]
I  forgot to execute docker-compose up -d.

Thank you for your support.

Thanks & Regards
Jagrut Dave

**Comment by syntropo** [comment]
Great - easy fix :)
