### ISSUE TITLE
Fetch docker containers with multi-hosts

### ISSUE THREAD

**Issue by Themex** [moviemasher/angular-moviemasher#35]
Hello!
Is there a simple way to run angular-moviemasher (as preview) and moviemasher.rb (as render) on two different machines without using SQS and S3, but docker?

**Comment by Themex** [comment]
No, I mean is there a way that one machine runs moviemasher.rb, another runs angular-moviemasher with no AWS?

**Comment by syntropo** [comment]
Ah, when running in Docker it's expected the shared volume mechanisms will work. There is currently no REST API or other mechanism to allow additional communication between the projects. It was removed for security concerns, but easy enough to add back in. You'd just utilize the web server running on the moviemasher.rb instance to support REST and then place jobs in its queue directory for processing.

**Comment by Themex** [comment]
Could you help to choose an old version with this feature that I could easily implement this, pls?

**Comment by syntropo** [comment]
The version that supported a REST API is long gone - it was before the whole system was ported from Flash to JavaScript. Again, Apache is running on the instances so you could create a PHP script that supported a REST interface. This script would simply place the jobs in the local queue directory for processing.

**Comment by Themex** [comment]
OK, thx
