### ISSUE TITLE
Issue with uploading video from  webcam (.webm)

### ISSUE THREAD

**Issue by rashinp** [moviemasher/angular-moviemasher#37]
We are trying to upload videos from Webcam (.webm files) feed via browser to moviemasher. The original recording (original.mp4) do get uploaded, and images are generated, however
1. image count starts from 1.jpg instead of 0.jpg, hence thumbnail is not displayed.
2. it doesn't generate audio 
3. duration shows as 0
4. doesn't playback on the moviemasher interface.

**Comment by syntropo** [comment]
I'm sorry to hear you're having problems uploading webm files. Are there any hints in the logs? Specifically you'd want to look for the ffmpeg commands that create the image sequence and MP3 soundtrack.
