### ISSUE TITLE
How to remove docker part on this project

### ISSUE THREAD

**Issue by TharakaRumeshJeewantha** [moviemasher/angular-moviemasher#38]
I downloaded Angular-MovieMasher on GitHub and I tried to run it on my WAMP and XAMPP server. But It must need to some configuration. please can you tell me how to do this configurations and I want to remove docker part on this project. please help me to do this.

![aaa](https://user-images.githubusercontent.com/25604416/49323745-17c36f80-f546-11e8-8f9c-6de3cdb1486e.PNG)

**Comment by syntropo** [comment]
You'll want to read through the 'Installation' and 'Install on your web server' sections of the README for this project. Please understand that the moviemasher.rb must also be utilized, but should be installed on a separate server since it is so resource intensive.

**Comment by TharakaRumeshJeewantha** [comment]
Thank you Syntropo your advice.

This moviemasher can upload movie clips using drag and drop, but please can you tell me how to upload movie clips to the moviemasher from using button upload/import.

**Comment by TharakaRumeshJeewantha** [comment]
and please tell me what is the folder and file structure for moviemasher, which run on local server.

**Comment by TharakaRumeshJeewantha** [comment]
as well please kindly tell me how to run this project on ubuntu without docker. and what is the file and folder structure. 

Thank you

**Comment by syntropo** [comment]
Regarding uploading, we're using the angular-file-upload node module - check their documentation. I'm not sure how I could explain the 'folder structure' - do you have a specific question about it? If you'd like to install for yourself without docker, you might want to follow the steps taken in the Dockerfile.

**Comment by TharakaRumeshJeewantha** [comment]
Dear sir

Can you tell me how to change moviemasher.ini  file (sample file) and how
to do the VOLUME configuration part in dockerfile. Please sir I am a newly
developer and I have no any idea about that docker. Therefore actually I
have no idea for how to remove docker on that project. Please if you have
free time, tell me what are the file I want to change and if you can,
please send me the sample files for change

Thank you
Best regards

**Comment by TharakaRumeshJeewantha** [comment]
Sir,

I do the some part of the DOCKERfile. but I cannot understand this selected
command to run. therefore please sir help me to do this selected things. I
attached file below.. and I want to know sir only I need to change
moviemasher.ini file or I need to change another files to remove docker in
this project? If you have a time, please send me are sample changed
moviemasher.ini file sir.

Thank you.
Regards
