### ISSUE TITLE
How to upload video clip from database

### ISSUE THREAD

**Issue by TharakaRumeshJeewantha** [moviemasher/angular-moviemasher#41]
how to upload video clip from database like mysql

**Comment by TharakaRumeshJeewantha** [comment]
Hello

can you tell me what is the ng-controller of that project? I couldn't find that.

**Comment by syntropo** [comment]
The top tier module is ammUi.

**Comment by TharakaRumeshJeewantha** [comment]
Thank you. please kindly tell me in Docker removing process..

![do](https://user-images.githubusercontent.com/25604416/50200045-30bb8580-037a-11e9-9e4f-2c10200619bf.PNG)

I cannot understand these highlighted steps to do. please tell me what are the means of that process and how to run this steps in ubuntu.

Thank you

**Comment by syntropo** [comment]
The VOLUME steps are just establishing shared mounted volumes between this and the moviemasher.rb container (not necessary if using SQS to queue jobs). The COPY command is just making a copy of the php.ini file so that PHP loads it in the container (you could just make the required changes to your php.ini file instead).

**Comment by TharakaRumeshJeewantha** [comment]
how to run the VOLUME command. I think it is not a ubuntu terminal command. please tell me how to run this VOLUME command

**Comment by syntropo** [comment]
It's a docker command and I'm telling you it's not needed if you're using SQS to queue jobs, which you likely will be unless you're using some alternate queueing mechanism.

**Comment by TharakaRumeshJeewantha** [comment]
well. I not using SQS and I run on this project local. then what are the steps should I follow?

**Comment by TharakaRumeshJeewantha** [comment]
actually I want to remove docker part on this project and I want to run this project on my local server. therefore I followed this steps in dockerfile. but I couldn't success so far

**Comment by syntropo** [comment]
Can I just ask why you're running locally without docker? The docker stuff is there specifically to make local development easy.

**Comment by TharakaRumeshJeewantha** [comment]
Because, my other project tasks (functions) run on local server in ubuntu. Therefore I want to integrate those all things in my local server like LAMPP

**Comment by syntropo** [comment]
Ultimately, what do you plan on doing with the installation? Is this just an academic exercise, or do you plan on actually deploying?

**Comment by TharakaRumeshJeewantha** [comment]
It is an academic exercise. My system mainly base on php, jquery and mysql database. I run it on Apache server. I recorded some videos on my system and I saved it on my server side folder. Then I planned to get those videos from this editor to edit. 

Now problem is my main system run on apache server in ubuntu and moviemasher editor run with docker. I have no good knowledge about docker, therefore I couldn’t integrate my system with this editor so far. 

I not plan to host in AWS server so far, therefore I want to integrate and run this whole project on my local apache server. Then I will decide to host 😀. 

Please help me to integrate my project with this editor, because actually I have no docker knowledge

**Comment by syntropo** [comment]
I'm afraid this just isn't a supported use case for Movie Masher. Great effort went into providing the AWS AMI for hosted sites and the Docker images for local development. The Docker images were specifically created to avoid the platform specific issues you are encountering.

**Comment by TharakaRumeshJeewantha** [comment]
😲😲how can I integrate this moviemasher to my project? Now I run my project on apache server and then separately  up the docker in terminal. But as I think it should be not a good way. Because my project and moviemasher run on separately.

Please give me an idea for integrate these 2 in 1 project.

Or please tell me an idea for how to run this moviemasher on apache server 😟😔

**Comment by syntropo** [comment]
Again, the system is NOT intended to be run alongside apache on the same box, except for local testing. For this testing, if you just run moviemasher.rb project in Docker then you could potentially mount the directory it's polling for jobs and add them to it. But this is not easy - far easier to run both projects within Docker so they are preconfigured to share the directories they need to.
