### ISSUE TITLE
How to run on Ubuntu and how to saving export video

### ISSUE THREAD

**Issue by Hasanthini** [moviemasher/angular-moviemasher#42]
Thank you for your quick response.. I completed 2nd issue is successfully. but I want to know sir is it enough to change only export_complete.php file or I need to change some another files like moviemasher.ini to change save location?

And my another problem is Now I run this project on DOCKER and I used to docker-compose up -d command and docker-compose down -v commands. But sir, I want to run this moviemasher project on my LOCAL web server on ubuntu. If it is possible to do, please sir tell me how to do this?

Thank you

**Comment by Hasanthini** [comment]
Hello
in angular moviemasher, I tried to change export folder. I want to export final edited video to the `export/videos` location.  I change the `user-media` directory to `export/videos` in `moviemasher.ini` file. but it does not work. can you tell me how can I save the my edited videos to the my locations

**Comment by syntropo** [comment]
You seem to be taking the correct steps. Could you be more specific about which part of the process is not working?

**Comment by Hasanthini** [comment]
First of all I installed docker on my ubuntu. Then automatically docker maked a directory in ‘var/lib’ on my ubuntu.

Then I maked the ‘user-media’ directory in my project and set it path on ‘moviemasher.ini’ file.

Now I tried to run moviemasher using ‘docker-compose up -d’  command. 

But, problem is my edited video not saved in my directory and it saved on separate place under my default docker folder in ‘var/lib’ 

I couldn’t change this saved location to my path (location). Every time my videos saved on default docker directory.

**Comment by syntropo** [comment]
Docker made a directory on your local machine at /var/lib?? Or where exactly? Are you sure that didn't happen after you ran the up command? What is the path of user-media directory? Is it within the angular container or somewhere else?

**Comment by Hasanthini** [comment]
(a) First of all I installed docker and docker-compose on my ubuntu.
(b) I changed the moviemasher.ini file to `web_root_directory = /var/www/html/` 
(c) I make a directory `mkdir -p -m 0777 /var/www/html/user-media`
(d) I used command `cd /var/www/html/angular-moviemasher/config/docker/development/`
(e) then `docker-compose up -d`
(f) then I edited the video and finally I saved and rendered it.

then I saw the my `user-media` directory, but I couldn't see the anything this directory. but I could find my edited video in this location `var/lib/docker/volumes/<uid-garbage value>/_data/user-media`

I cannot understand what is the reason of that and. I want to save my edited videos to the my own location. please help me

Thank you

**Comment by syntropo** [comment]
Sounds like you made the /var/www/html/user-media directory on your host machine? The docker containers cannot see that unless it's mounted somehow in the docker-compose.yml file.

**Comment by Hasanthini** [comment]
my `docker-compose.yml` file like this. what I want to change please..

![capture2](https://user-images.githubusercontent.com/45619371/50624181-7dd75400-0f43-11e9-9497-58903894f058.PNG)
