### ISSUE TITLE
Can I set the Video clips initially load in this angular-moviemasher

### ISSUE THREAD

**Issue by johnedinson** [moviemasher/angular-moviemasher#44]
HELLO GUYS

Tell me, How can I set the my video clips initially load automatically in angular-moviemasher. (some video clips load under the video with moviemasher start up). can I do this? If can I dothis, How can I do this. because As I think, this is not has a json upload.

**Comment by syntropo** [comment]
The items appearing in the media browser are controlled by the script at angular-moviemasher/app/php/media.php which ultimately calls the data_search function in angular-moviemasher/app/php/include/datautils.php. You could override this function to supply different JSON payload for videos or perhaps create a new group that just displays your videos.

**Comment by johnedinson** [comment]
Hello Syntropo

well. thank you for your response. but I have no good understand about that. If you have a some free time, please tell me how to show my json file video on this moviemasher. 

{
		"id": "161",
		"module": "testl",
		"lecture_hall": "503",
		"image_path": "saved\/503\/2018-12-06\/testl_402.jpg",
		"adate": "2018-12-06",
		"videos": [{
			"id": "401",
			"file_path": "saved\/503\/2018-12-06\/testl_401.mp4",
			"image_path": "saved\/503\/2018-12-06\/testl_401.jpg"
		}, {
			"id": "402",
			"file_path": "saved\/503\/2018-12-06\/testl_402.mp4",
			"image_path": "saved\/503\/2018-12-06\/testl_402.jpg"
		}]
	}

this is my sample json file. Now I want to display this "file_path" videos under "videos" in json file. how can I do this?

**Comment by syntropo** [comment]
The videos need to be preprocessed into image sequences with mp3 soundtracks before displaying in the editor.

**Comment by johnedinson** [comment]
can you tell me the steps?

**Comment by johnedinson** [comment]
in this editor, automatically decode the audio and images of the our uploaded video. but I tried to upload video from json file or my database, I couldn't do this process. because I couldn't find the this function. anyone please help me to upload this videos to the editor from the my json file

**Comment by syntropo** [comment]
Well, 'http:localhost/abc/xyz.json' is a not a valid URL and even if it were, we're looking for a file path in $path rather than a localhost URL.

**Comment by johnedinson** [comment]
1. Ok. I placed the my json file in a directory and give the it’s path to $path. But my video clip not display with moviemasher loading.. 

2. How can I Upload the my database video to the editor (what is the decode function )

Please tell me

**Comment by syntropo** [comment]
Regarding your first question... are you sure the JSON parses correctly? Check both the web server logs and javascript console for relevant errors. 

I don't understand your second question. Again, all videos must be preprocessed (encoded) before use in the editor. Decoding means rendering the mash into a true video file.

**Comment by johnedinson** [comment]
My second question is how to upload videos from database or json files?

**Comment by syntropo** [comment]
You literally have a video binary stored in your database or JSON file? Or do you have a file stored somewhere and its location stored in your database or JSON file? 

Assuming the later, you just need to construct an import job that provides the location and any authentication that might be needed to retrieve it. Check out the api_import function in apiutils.php file.

**Comment by johnedinson** [comment]
yer, I used mysql database and I passed my data into json format. it is like a url (example: http://localhost/abc/xyz.json) 

yer I remove the authentication part and I used it to static name

**Comment by syntropo** [comment]
The system does not support localhost URLs - if it's on the same box as moviemasher.rb then you can provide a file URL or just a non-relative file path.

**Comment by johnedinson** [comment]
ok fine. I got my json file and saved it on my `angular-moviemasher/app/php/include/xyz.json` directory and give this path to the `datautils.php`. is it correct or fine?

**Comment by johnedinson** [comment]
actually my requirement is :
I saved my videos on another folder called `saved` in my server. then I want to get or call these videos to the `angular-moviemasher` editor and then I want to edit and saved them.

**Comment by syntropo** [comment]
If the files are on a web server then why not supply the URL to them? Again, you need to construct an import job that provides the location and any authentication that might be needed to retrieve it. Check out the api_import function in apiutils.php file.

**Comment by johnedinson** [comment]
Well. `If the files are on a web server then why not supply the URL to them?` because my project run on localhost 80 port Apache server and editor run on localhost 8080 port docker. my `saved` directory on my Apache server. now I want to pass this video under this folder to the moviemasher editor. 

yer, I saved the path (location) on my database and json file.

**Comment by syntropo** [comment]
I'm not sure I understand what you're tying to do... If everything is running within Docker then you can use the shared volumes functionality to mount one of them between the two containers and use the local client. Otherwise you could just treat localhost running on port 80 as any other destination in the job JSON.

**Comment by johnedinson** [comment]
My simple question is how to upload the database (mySql) videos to the moviemasher.

I saved videos path (location) on my database column. 😢

**Comment by syntropo** [comment]
Obviously, you've asked this question before and not been satisfied with my answers. Perhaps if you rephrased it?

**Comment by johnedinson** [comment]
Hello Guys
As I think, This moviemasher contains two docker images `moviemasher.rb` and `angular-moviemasher`. I am planing to host this app using local web server like cPanel. (I am not hoping to use AWS server). but I have no big idea to the how to host this two docker images on my local web server.

As I think I must need to merge this two docker images. please anyone tell me how can I host this app in my local server

**Comment by syntropo** [comment]
What you're trying to do should not really be done because the moviemasher.rb project is too resource intensive to run alongside a web server. Typically folks will use a cluster of machines running moviemasher.rb so jobs do not have to be processed one after another. The web server only posts jobs into some sort of queue that they address. 

If you're desperate to have it all run on one machine for testing, running Docker is really the easiest way. Alternatively you can try to replicate the steps taken in the Dockerfile within moviemasher.rb in order to install all the software the ruby scripts utilize. This is MUCH harder.

**Comment by johnedinson** [comment]
I understood and Thanks for your great ideas. 

01. But please can you tell me how can I host this angular-moviemasher on my own web server. because I not using AWS server. I plan to use cPanel to host this.

02. And How can I integrate this MM with other project. my one of another project based on php run on my ubuntu apache server and I want to integrate this to MM project. Is it difficult or easy?   

03. As I think You have no idea about my project. therefore actually my project is video recorder. I used WebRTC and Kurento media server to record the video and I save it on my server side folder. then I plan to get this videos from this MM to edit.

**Comment by syntropo** [comment]
Getting angular-moviemasher integrated into your project should not be terribly difficult. Getting moviemasher.rb installed on that same box would be extremely difficult and impractical for all but the simplest testing scenarios. If you don't install moviemasher.rb on a separate box it will drastically slow down your web server. If you don't install moviemasher.rb on multiple boxes only one video can be transcoded at a time.

**Comment by johnedinson** [comment]
ok please tell  me what is the easy way to integrate my project with this MM and how can I host this. If you can, please tell me easy way with steps to that process

**Comment by syntropo** [comment]
I have already explained how to do this. I'm sorry I can't provide hand holding for unsupported installations.
