### ISSUE TITLE
Issue with rendering at 1920x1080

### ISSUE THREAD

**Issue by kushan2** [moviemasher/angular-moviemasher#47]
I rendered video with passing resolution of dimensions='1920x1080' and video_rate = 30. it gives me an following error. Do you have any idea.

failed to see if 3.0 == duration of /tmp/moviemasher/render/c1e692a6-109d-4cf0-bbf8-941966eede8d/f6709189-ca7e-4054-9c70-05b36b3eccb8.mp4
ffmpeg -y  -loop 1 -i /tmp/moviemasher/download/c15d38333d722f8c8a2fd9667f426697b00c74bd7109be41866e874e46aa7009/downloaded.png -filter_complex "color=color=0x000000:duration=3.0:size=1920x1080:rate=28[layer0];color=color=\#ffffff:size=1920x1080:duration=3:rate=28,drawtext=fontcolor=0xff0000@1.0:shadowcolor=0x000000@0.0:fontsize=324:x=0:y=0:shadowx=29:shadowy=16:fontfile=/tmp/moviemasher/download/4963dad43ca77bb16a721c3690198ec900597b13222d32505e05fcd087992e68/downloaded.ttf:textfile=/tmp/moviemasher/render/c1e692a6-109d-4cf0-bbf8-941966eede8d/f6709189-ca7e-4054-9c70-05b36b3eccb8/d7b3986c-e8ec-49b1-94e9-c1cbaa29205b.txt,scale=width=1920:height=1080,setsar=sar=1:max=1[layer1];[0:v]setpts=expr=PTS-STARTPTS,scale=width=771.7281553398059:height=198.72,setsar=sar=1:max=1[layer2];[layer0][layer1]overlay=x=0:y=0[layered1];[layered1][layer2]overlay=x=0.955\*\(1920-overlay_w\):y=0.939\*\(1080-overlay_h\)" -t 3.0 -an -s 1920x1080 -c:v libx264 -level 41 -movflags faststart -b:v 2000k -r:v 28 -metadata title\=Part\ 1 /tmp/moviemasher/render/c1e692a6-109d-4cf0-bbf8-941966eede8d/f6709189-ca7e-4054-9c70-05b36b3eccb8.mp4

**Comment by syntropo** [comment]
Seems like it might be having trouble rendering the text - is the font a custom one?

**Comment by kushan2** [comment]
Thank you for the replay. No, its default text from the Themes(Title).

**Comment by kushan2** [comment]
Also if I only added video and render, it gives me following error on that resolution,

couldn't create \/tmp\/moviemasher\/render\/68a6b5f5-739b-46dc-b498-211a8a9af79c\/55393f1c-157e-4e6b-b7a4-7c023f787d2a.mp4\nffmpeg -y -i \/tmp\/moviemasher\/download\/05a13c9772bb09c000a128b1f441061d419dc8759547c9e689b6d79a578dfa8f\/downloaded.mp4 -loop 1 -i \/tmp\/moviemasher\/download\/c15d38333d722f8c8a2fd9667f426697b00c74bd7109be41866e874e46aa7009\/downloaded.png -filter_complex \"color=color=0x000000:duration=23.9:size=1920x1080:rate=50[layer0];[0:v]trim=duration=23.9,fps=fps=50,setpts=expr=PTS-STARTPTS,scale=width=1920:height=1080,setsar=sar=1:max=1[layer1];[1:v]setpts=expr=PTS-STARTPTS,scale=width=771.7281553398059:height=198.72,setsar=sar=1:max=1[layer2];[layer0][layer1]overlay=x=0:y=0[layered1];[layered1][layer2]overlay=x=0.955\\*\\(1920-overlay_w\\):y=0.939\\*\\(1080-overlay_h\\)\" -i \/tmp\/moviemasher\/download\/05a13c9772bb09c000a128b1f441061d419dc8759547c9e689b6d79a578dfa8f\/downloaded-intermediate.wav -af \\[0:a\\]atrim\\=start\\=0.0:duration\\=23.9\\,asetpts\\=expr\\=PTS-STARTPTS -async 1 -t 23.9 -b:a 224k -r:a 44100 -c:a aac -s 1920x1080 -c:v libx264 -level 41 -movflags faststart -b:v 4000k -r:v 50 -metadata title\\=Part\\ 1 \/tmp\/moviemasher\/render\/68a6b5f5-739b-46dc-b498-211a8a9af79c\/55393f1c-157e-4e6b-b7a4-7c023f787d2a.mp4

**Comment by syntropo** [comment]
Does it work at other standard resolutions? Not all sizes are necessarily supported by all output formats.

**Comment by kushan2** [comment]
yes, all other resolutions work. Is that can be because of server issue? Memory or something? seems like it is rendering @1080 if the clip length is less than 1secound.

**Comment by syntropo** [comment]
I think both dimensions need to be divisible by 16

**Comment by kushan2** [comment]
ok. Let me try with that.

**Comment by kushan2** [comment]
I clean everything and started docker again. Also upgraded the server RAM and change output to 1920x1072. Now its working.

**Comment by kushan2** [comment]
its working now.
