### ISSUE TITLE
Uploading stopped at 51% on the app run in localhost

### ISSUE THREAD

**Issue by thetn2** [moviemasher/angular-moviemasher#48]
Hello,

Using attached configuration, i setup the MovieMasher on localhost with XAMPP.
I followed the below manual.
[https://github.com/moviemasher/angular-moviemasher#how-to-install-on-your-web-host](url)

I was able to run the app successfully. But there is an error in uploading. The progress is showing 51% and stopped.

"import_monitor.php" is responding below json every 10 seconds and the job is never completed. The progress is always 0.01. Please see below log.
`{"completed":0.01,"status":"Queued","ok":1}`

[angular-moviemasher.log](https://github.com/moviemasher/angular-moviemasher/files/4791488/angular-moviemasher.log)

**Question:**
As I see there are a lot of files inside queue folder, Do I need to run any php or ruby program in background to process those queue files?
Or Any tutorial link that i can follow how to setup in localhost?

[moviemasher.ini.txt](https://github.com/moviemasher/angular-moviemasher/files/4791384/moviemasher.ini.txt)

![image](https://user-images.githubusercontent.com/67048644/84878721-cb566b00-b0bc-11ea-8358-a1ca083788b0.png)

Thanks,
Naing

**Comment by syntropo** [comment]
Yeah, you need to be running moviemasher.rb somewhere - given that configuration, you'd want it running on the same box.
