### ISSUE TITLE
[Feature]: MJPEG decode support

### ISSUE THREAD

**Issue by conor-mac-aoidh** [moviemasher/angular-moviemasher#5]
It would be very useful if the player supported playback of concatenated JPG files in the MJPEG format.

This would mean that the entire video clip could be downloaded at once, rather than a separate HTTP request for each frame. The playback of images decoded directly from the MJPEG file should improve the performance of the player.

This could be done using image data URIs - a base64 encoded URI format for displaying image data:

https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs

And a cross-browser MPEG Decoder for JavaScript:

https://github.com/SaschaNaz/MJPEGDecoder

Here is a simple demo of the concept in action:

http://poohbot.com/2013/11/14/play-motion-jpeg-video-using-javascript-in-browser-no-plugins-minimal-js/

Though this example does not work in all browsers (chrome works for me), the MJPEGDecoder project apparently does.

Any thoughts on this? If you think it would fit in well with the angular-moviemasher project, I might do some work on adding this functionality.

Conor

**Comment by syntropo** [comment]
This was explored previously, when porting to JavaScript... Keeping in mind that this is a video editor and not a video player, what is the use case here? Are we hoping to avoid preprocessing, rendering, or both? We load image based frames instead of raw video specifically to avoid having to load the entire video file at once when previewing any particular spot in the timeline.

**Comment by conor-mac-aoidh** [comment]
Hmm i didn't think about the seeking issue. But I'm not sure it will be a massive issue (in my use case), as I'm working with a large number of small clips. If we were using MJPEG, you could simply jump to the appropriate clip and begin decoding. Decoding would only need to happen once, and decoded JPEGs could be stored in memory.

The reason I want to use MJPEG, is to prevent against uploading/downloading tens of images for every clip. I'm working on a mobile device and trying to limit HTTP connections. Also, in this case I am not using MJPEG for playback - I'm simply using it as an intermediary format. When the MJPEG is downloaded on device, it is passed into the ffmpeg image2 demuxer to generate an MP4 video for the preview. Turns out this is much faster than downloading an mp4 file, as this usually requires a full re-encode to the desired format/resolution.

However, we are still using angular-moviemasher for the website video preview. So, I was thinking if the website could use MJPEG also, that I could have one format used for all devices. I still think that although there is some decoding overhead, that this is worth it for only using one HTTP call to download the clip. Also, I'm talking about very low quality preview resolutions here, so the file size is not massive. I suppose only actually implementing and testing the thing will definitively show which method is better - JPG or MJPG.

But, I'm willing to give it a try and see!

**Comment by syntropo** [comment]
Well, if the decoded JPEGs are stored in memory then it's not true that they would only be decoded once... The timeline is constantly combing through the cache looking for individual frames to unload. Reloading them later would then be a matter of downloading the video again and decoding. To avoid the extra download we could create yet another cache of videos that might be decoded, but it's hard to say when would be a good time to unload these. Either way this adds a lot of overhead to the whole caching mechanism. 

If it's more convenient on the client to upload a video containing jpeg frames, then why not just do that? This video would be preprocessed like others, resulting in individual frames that can be managed with the existing mechanism. 

If you're making an app, you might consider creating some mechanism within it that more or less mocks a web server fulfilling requests for frames by grabbing them from a video. I believe webkit offers the ability to create custom protocol handlers, so this might be possible without making changes to moviemasher.js which actually does the requesting.
