### ISSUE TITLE
Charges when service was not being used

### ISSUE THREAD

**Issue by freudianslip27** [moviemasher/angular-moviemasher#8]
Hello,

A few months ago we wanted to test a service, called Movie Masher.  We were under the understanding that we would be charged only when it was being used.  A week later we decided to use a different software to work with video.  Unfortunately I forgot it was added to the S3 service.

Months later I do a review and to my shock we have been charged hundreds and hundreds of dollars!  For something we haven't even used since that week in September.  If you look at the records, you will see we haven't used it, yet we are being charged for every single hour each month.  

We have stopped it now, is there anything you can do?  Did something go wrong here?  Thank you for your help!  

Matt

**Comment by syntropo** [comment]
I'm sorry you've had AWS troubles - please understand you've been charged by Amazon for services of theirs you've consumed, even if unwittingly, so you need to contact them for billing support. If you're into the realm of hundreds of dollars then it's probably for more than S3 hosting services - you likely launched EC2 instances that you didn't shut down. If you used the Deployment Wizard on moviemasher.com to launch instances through CloudFormation, you need to shut them down there too. To stop being charged for S3 services, simply delete the movie masher labeled buckets.
