### ISSUE TITLE
s3 bucket url

### ISSUE THREAD

**Issue by bjarman** [moviemasher/angular-moviemasher#9]
I'm having problems uploading to my s3 bucket.
I'm hosting the angular-moviemasher on our own server and the rb is hosted by amazon together with a queue and a bucket.
UI says "Problem uploading undefined".
Firebug console says net::ERR_NAME_NOT_RESOLVED on the s3 bucket url.
The url used differs from the endpoint in the bucket properties at amazon.
Amazons suggested endpoint looks like this:
"mybucketname".s3-website.eu-central-1.amazonaws.com
but the url used looks like this:
s3.eu-central-1a.amazonaws.com/"mybucketname"
("mybucketname" translates to whatever I use in moviemasher.ini)

I'm not sure what might be wrong in this case but since the URL's differ I thought I might ask here to see if anyone has had a similar problem.

**Comment by syntropo** [comment]
You might try using a bucket that has not been designated as a 'website' in S3.

**Comment by bjarman** [comment]
The bucket I am using actually has not been enabled for "website hosting" if that is what you mean?
There are three configuration options regarding this in s3:
1. Do not enable website hosting
2. Enable website hosting
3. Redirect all requests to another host name
Currently number one is checked for my bucket.

The error I get seems to have something to do with the link generated to the bucket:
https://s3.eu-central-1a.amazonaws.com/"mybucketname"/...

This url results in:
s3.eu-central-1a.amazonaws.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

So, I dabbled a bit with the region property and removed the "a" from eu-central-1 and now I am getting somewhere - a new error in Chrome:
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Could it be that i need some CORS-stuff in the ajax request?

**Comment by syntropo** [comment]
I suggested that the website option had been checked, because Amazon is recommending an address that includes 'website'. I believe the requests do use CORS, so you might try setting that up for your bucket.

**Comment by bjarman** [comment]
Ok, so I have created a CORS configuration and now things are working better. 

The files are uploaded to the bucket but right after that I get this error message in the client:

"could not cache http://"mybucket".s3-website.eu-central-1.amazonaws.com/user-media/myinstance/4C702B5E-C1C5-4C5F-924C-D60B3AF8AA5D/mymovie.mov"

Loking in the bucket the movie is created in user-media/myinstance-id/original.mov as should but then something goes wrong and the above message is displayed in red text below the drop zone in the client.

So - close but no cigar - yet :)

Any hints?

**Comment by syntropo** [comment]
You've managed to upload the file, but then it couldn't be retrieved by the transcoder instance. What are the permissions of the file? How is it being requested? Again, your URL contains 'website' - why is this?

**Comment by bjarman** [comment]
Ok, I have come a bit further, I think. Created some policies etc and removed the "website" from the user_media_host But now I get the error  "no implicit conversion of nil into String" which seems to be a known problem already with an open issue.

**Comment by syntropo** [comment]
If S3 is telling you to put 'website' in your URL, removing it in Movie Masher will not fix anything. I mention this because S3 does not typically tell you to put 'website' in the URL unless you've configured the bucket to be a web site. You might try with a bucket that you are sure hasn't been configured as a web site, since this can complicate the building of URLs within Movie Masher.

**Comment by bjarman** [comment]
I understand this, however I do not think that the bucket is/was configured to be a website - actually the only property I can find that seems to have anything to do with this is under the "Static website hosting" tab and the checked/chosen alternative in my bucket is: "Do not enable website hosting".

Is there any other place in s3 where one can configure the bucket to be a website - I cannot find it if so.

Removing the "website" from the user_media_host actually got me forward now only facing the "no implicit conversion of nil into String" error for which there is another active issue - so I am optimistic about this :)

**Comment by syntropo** [comment]
Yes, check the other issue ticket to see if that fix works for you.
